# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'primera_app.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Contadordeclicks(object):
    def setupUi(self, Contadordeclicks):
        Contadordeclicks.setObjectName("Contadordeclicks")
        Contadordeclicks.resize(202, 382)
        self.titulo = QtWidgets.QLabel(Contadordeclicks)
        self.titulo.setGeometry(QtCore.QRect(0, 20, 201, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.titulo.setFont(font)
        self.titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo.setObjectName("titulo")
        self.contador = QtWidgets.QLabel(Contadordeclicks)
        self.contador.setGeometry(QtCore.QRect(50, 60, 91, 71))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(50)
        font.setBold(True)
        font.setWeight(75)
        self.contador.setFont(font)
        self.contador.setFrameShape(QtWidgets.QFrame.Box)
        self.contador.setAlignment(QtCore.Qt.AlignCenter)
        self.contador.setObjectName("contador")
        self.btnClick = QtWidgets.QPushButton(Contadordeclicks)
        self.btnClick.setGeometry(QtCore.QRect(60, 150, 71, 23))
        self.btnClick.setObjectName("btnClick")
        self.label_3 = QtWidgets.QLabel(Contadordeclicks)
        self.label_3.setGeometry(QtCore.QRect(40, 190, 111, 171))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/Imagenes/479px-Théophile-Alexandre_Steinlen_-_Tournée_du_Chat_Noir_de_Rodolphe_Salis_(Tour_of_Rodolphe_Salis\'_Chat_Noir)_-_Google_Art_Project.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Contadordeclicks)
        QtCore.QMetaObject.connectSlotsByName(Contadordeclicks)

    def retranslateUi(self, Contadordeclicks):
        _translate = QtCore.QCoreApplication.translate
        Contadordeclicks.setWindowTitle(_translate("Contadordeclicks", "Contador de clicks"))
        self.titulo.setText(_translate("Contadordeclicks", "Contador de Click"))
        self.contador.setText(_translate("Contadordeclicks", "0"))
        self.btnClick.setText(_translate("Contadordeclicks", "Haz Click"))
from Imagenes import source 


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Contadordeclicks = QtWidgets.QWidget()
    ui = Ui_Contadordeclicks()
    ui.setupUi(Contadordeclicks)
    Contadordeclicks.show()
    sys.exit(app.exec_())
